# Generated by Django 5.1.7 on 2025-03-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='first_time_users_only',
            field=models.BooleanField(default=False),
        ),
    ]
